hokuyo_lidar_driver_node:
  ros__parameters:
    ip_address: "192.168.0.10"
    ip_port: 10940
    laser_frame_id: "laser"
    calibrate_time: true
    default_user_latency: 0.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    get_detailed_status: false
    publish_intensity: true
    publish_multiecho: false
    cluster: 1
    skip: 0
