slam_node:
  ros__parameters:
    # ROS Parameters

    # normally, you don't need to alter the params below

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss

    # laser scan related params
    scan_topic: /scan
    scan_queue_size: 5              # buffer up to 5 scans for tf filter lookup
    use_map_saver: true

    debug_logging: false
    throttle_scans: 1
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 10.0           # for rastering images
    minimum_time_interval: 0.1      # Not used in async mode. In sync mode, this downsamples the scan to 10Hz
    transform_timeout: 0.5
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000     # program needs a larger stack size to serialize large maps
    enable_interactive_mode: false

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true       # false?
    minimum_travel_distance: 0.     # unset this value as we are depending on scan-matching for odometry
    minimum_travel_heading: 0.      # unset this value as we are depending on scan-matching for odometry
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    # set resolution such that dimension/resolution is an even integer, else libkarto will crash
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 2.   # 4x this value as we are depending on scan-matching for odometry
    angle_variance_penalty: 4.      # 4x this value as we are depending on scan-matching for odometry

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    use_lifecycle_manager: false
